spring.application.name=movies
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
spring.liquibase.change-log=classpath:db/changelog-master.xml
logging.level.liquibase=INFO
spring.liquibase.contexts=development
#
logging.level.org.springframework.jdbc=WARN
logging.level.org.springframework.data=WARN
logging.level.org.springframework.orm=WARN
logging.level.org.springframework.hibernate=WARN
#
logging.level.org.springframework.web:DEBUG
#
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
#
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
# jwt
#secret tunnel, secret tunnel secret tunnel though the mountains
#*s3r3t7unn3!53crR3tTunn3L$ecr377Un3I+7houGh7h3M0unt41n$
#https://www.devglan.com/online-tools/hmac-sha256-online?ref=blog.tericcabrel.com
security.jwt.secret-key=760d061bff7167e8585627ac1de8126776b944e85268a9d86b6021ce236e328c
# 1h in millisecond
security.jwt.expiration-time=86400000

